=== AlexBarca/JD2018-04-11/src/by/it/tayanovskii/jd02_09/Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it.by/tayanovskii/xmlschema"
        xmlns:tns="http://it.by/tayanovskii/xmlschema"
        elementFormDefault="qualified">
    <element name="Readers">
        <complexType>
            <sequence>
                <element name="Reader"
                         type="tns:Reader"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Reader">
        <sequence>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Email" type="string"/>
            <element name="Publications" type="tns:Publications"/>
        </sequence>
    </complexType>

    <complexType name="Publications">
        <sequence>
            <element name="Publication"
                     type="tns:Publication"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Publication">
        <sequence>
            <element name="Title" type="string"/>
            <element name="Number" type="integer"/>
            <element name="Description" type="string"/>
            <element name="Date" type="string"/>
            <element name="Price" type="tns:Price"/>
        </sequence>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute
                        name="currency"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== AlexBarca/JD2018-04-11/src/by/it/tayanovskii/jd02_09/Readers+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Readers xmlns="http://it.by/tayanovskii/xmlschema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/tayanovskii/xmlschema Schema.xsd"
>
        <Reader>
            <Login>Ivanov</Login>
            <Password>qwerty12345</Password>
            <Email>Ivanov@yandex.ru</Email>
            <Publications>
                <Publication>
                    <Title>Пожарная безопасность</Title>
                    <Number>1</Number>
                    <Description>Контроль за пожарной безопасностью на предприятии</Description>
                    <Date>2018-06-10</Date>
                    <Price currency="USD">10.0</Price>
                </Publication>
                <Publication>
                    <Title>Охрана труда</Title>
                    <Number>3</Number>
                    <Description>Контроль за охраной труда на государсвенных предприятиях</Description>
                    <Date>2018-05-01</Date>
                    <Price currency="EUR">30.3</Price>
                </Publication>
            </Publications>
        </Reader>
        <Reader>
            <Login>Petrov</Login>
            <Password>12345qwerty</Password>
            <Email>Petrov@yandex.ru</Email>
            <Publications>
                <Publication>
                    <Title>Охрана правопорядка</Title>
                    <Number>7</Number>
                    <Description>Контроль за правопорядком в общественнх местах</Description>
                    <Date>2017-02-01</Date>
                    <Price currency="RUB">40.99</Price>
                </Publication>
                <Publication>
                    <Title>Охрана труда</Title>
                    <Number>2</Number>
                    <Description>Контроль за охраной труда на государсвенных предприятиях(июль 2018)</Description>
                    <Date>2018-07-01</Date>
                    <Price currency="BYN">30.5</Price>
                </Publication>
            </Publications>
        </Reader>

</Readers>
