=== AlexBarca/JD2018-04-11/src/by/it/shumilov/jd02_07/Elective/Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it.by/shumilov/xmlschema"
        xmlns:tns="http://it.by/shumilov/xmlschema"
        elementFormDefault="qualified">

    <element name="Students">
        <complexType><!--сложный-->
            <sequence><!--по порядку-->
                <element name="Student"
                        type="tns:Student"
                        maxOccurs="unbounded">

                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Student">
        <sequence>
            <element name="Person" type="tns:Person" maxOccurs="1"/>
            <element name="CoursesStudent" type="tns:CoursesStudent"/>
        </sequence>
    </complexType>

    <complexType name="Person">
        <sequence>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Email" type="string"/>
            <element name="FirstName" type="string"/>
            <element name="SecondName" type="string"/>
        </sequence>
    </complexType>


    <complexType name="CoursesStudent">
            <sequence>
                <element name="CourseStudent"
                         type="tns:CourseStudent"
                         maxOccurs="unbounded">
                </element>
            </sequence>
    </complexType>

    <complexType name="CourseStudent">
        <sequence>
            <element name="Course" type="tns:Course"/>
        </sequence>
        <attribute name="mark" type="int"/>
    </complexType>

    <complexType name="Course">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Subject" type="string"/>
            <element name="Start" type="date"/>
            <element name="End" type="date"/>
            <element name="Teacher" type="tns:Teacher"/>
        </sequence>
    </complexType>


    <complexType name="Teacher">

        <sequence>
            <element name="Person" type="tns:Person" maxOccurs="1"/>
        </sequence>
        <attribute name="department" type="string" use="required"/>
    </complexType>
</schema>

=== AlexBarca/JD2018-04-11/src/by/it/shumilov/jd02_08/Students_xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>

<Students xmlns="http://it.by/shumilov/xmlschema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/shumilov/xmlschema Schema.xsd" >


    <Student>
        <Person>
            <Login>Vasya</Login>
            <Password>pa$$word</Password>
            <Email>vas2018@mail.ru</Email>
            <FirstName>Vasilii</FirstName>
            <SecondName>Terkin</SecondName>
        </Person>
        <CoursesStudent>
            <CourseStudent mark="3">
                <Course>
                    <Name>Physics things</Name>
                    <Subject>Physics</Subject>
                    <Start>2018-01-12</Start>
                    <End>2018-05-12</End>
                    <Teacher department="Physics">
                        <Person>
                            <Login>Vit</Login>
                            <Password>pa$$word1</Password>
                            <Email>vit2018@mail.ru</Email>
                            <FirstName>Vitalii</FirstName>
                            <SecondName>New</SecondName>
                        </Person>
                    </Teacher>

                </Course>

            </CourseStudent>
            <CourseStudent>
                <Course>
                    <Name>Math things</Name>
                    <Subject>Math</Subject>
                    <Start>2018-01-12</Start>
                    <End>2018-07-12</End>

                        <Teacher department="Math">
                            <Person>
                                <Login>Stas</Login>
                                <Password>pa$$word3</Password>
                                <Email>stas2018@mail.ru</Email>
                                <FirstName>Stas</FirstName>
                                <SecondName>Lin</SecondName>
                            </Person>
                        </Teacher>

                </Course>
            </CourseStudent>
        </CoursesStudent>
    </Student>
</Students>
