=== AlexBarca/JD2018-04-11/src/by/it/kashayed/jd02_07/SDTD.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT Owners (Owner)+>
        <!ELEMENT Owner (Login,email,Password,Cars)>
<!ELEMENT Login (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Cars (Car)+>
<!ELEMENT Car (Model,Year,Price)>
<!ELEMENT Model (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== AlexBarca/JD2018-04-11/src/by/it/kashayed/jd02_07/Sales_DTD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Owners SYSTEM "SDTD.dtd">
<Owners>
    <Owner>
        <Login> Drakula </Login>
        <email> drakula@gmail.com </email>
        <Password>nightdrakula332</Password>
        <Cars>
            <Car>
                <Model>Pontiac GTO</Model>
                <Year>1965</Year>
                <Price>10000</Price>
            </Car>
        </Cars>
    </Owner>
    <Owner>
        <Login> Nikita </Login>
        <email> nikita13@gmail.com </email>
        <Password> blackhorse666</Password>
        <Cars>
            <Car>
                <Model>Nissan sunny</Model>
                <Year>1996</Year>
                <Price>1000</Price>
            </Car>
            <Car>
                <Model>Opel Astra</Model>
                <Year>1999</Year>
                <Price>2000</Price>
            </Car>
        </Cars>
    </Owner>
</Owners>
