=== AlexBarca/JD2018-04-11/src/by/it/zakharenko/jd02_07/Schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it.by/zakharenko/xmlschema"
        xmlns:tns="http://it.by/zakharenko/xmlschema"
        elementFormDefault="qualified">
    <element name="Clients">
        <complexType>
            <sequence>
                <element name="Client"
                         type="tns:Client"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Client">
        <sequence>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Email" type="string"/>
            <element name="Books" type="tns:Books"/>
        </sequence>
    </complexType>

    <complexType name="Books">
        <sequence>
            <element name="Book"
                     type="tns:Book"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="Book">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Name" type="string"/>
            <element name="Author" type="string"/>
            <element name="Genre" type="string"/>
            <element name="Language" type="string"/>
            <element name="Pages" type="integer"/>
            <element name="Price" type="tns:Price"/>
        </sequence>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute
                        name="currency"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== AlexBarca/JD2018-04-11/src/by/it/zakharenko/jd02_07/Clients+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Clients xmlns="http://it.by/zakharenko/xmlschema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/zakharenko/xmlschema Schema.xsd">
    <Client>
        <Login>Dima</Login>
        <Password>123984ytf</Password>
        <Email>dima12345@mail.ru</Email>
        <Books>
            <Book>
                <Description>
                    Интересная книга для любого возраста!
                </Description>
                <Name>
                    The Chronicles of Narnia
                </Name>
                <Author>
                    Clive Lewis
                </Author>
                <Genre>Fantasy</Genre>
                <Language>English</Language>
                <Pages>767</Pages>
                <Price currency="RU">167</Price>
            </Book>
            <Book>
                <Description>
                    Захватывающий детектив для любителей этого жанра!
                </Description>
                <Name>
                    The Adventures of Sherlock Holmes
                </Name>
                <Author>
                    George Newnes
                </Author>
                <Genre>
                    Detective story
                </Genre>
                <Language>English</Language>
                <Pages>307</Pages>
                <Price currency="EU">79</Price>
            </Book>
        </Books>
    </Client>
    <Client>
        <Login>Anna</Login>
        <Password>anna678</Password>
        <Email>anna3928@mail.ru</Email>
        <Books>
            <Book>
                <Description>
                    Шикарная книга о любви!
                </Description>
                <Name>
                    Pride and Prejudice
                </Name>
                <Author>
                    Jane Austen
                </Author>
                <Genre>Novel</Genre>
                <Language>English</Language>
                <Pages>416</Pages>
                <Price currency="US">193</Price>
            </Book>
            <Book>
                <Description>
                    Книга, которая заставляет задуматься о жизни!
                </Description>
                <Name>
                    Преступление и наказание
                </Name>
                <Author>Фёдор Достоевский</Author>
                <Genre>Роман</Genre>
                <Language>Русский</Language>
                <Pages>608</Pages>
                <Price currency="RU">118</Price>
            </Book>
        </Books>
    </Client>
</Clients>
