=== AlexBarca/JD2018-04-11/src/by/it/kurmaz/jd02_07/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://it.by/kurmaz/jd02_07/xmlschema"
        xmlns:tns="http://it.by/kurmaz/jd02_07/xmlschema"
        elementFormDefault="qualified">
    <element name="Clients">
        <complexType>
            <sequence>
                <element name="Client"
                         type="tns:Client"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Client">
        <sequence>
            <element name="Login" type="string" />
            <element name="Password" type="string" />
            <element name="Email" type="string" />
            <element name="Address" type="string" />
            <element name="Carma" type="string" />
            <element name="Order" type="tns:Order" />
        </sequence>
    </complexType>
    <complexType name="Order">
        <sequence>
            <element name="Cost" type="decimal" />
            <element name="Goods" type="tns:Goods" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    <complexType name="Goods">
        <sequence>
            <element name="Name" type="string" />
            <element name="Price" type="decimal" />
            <element name="Quantity" type="int" />
            <element name="CatalogIndex" type="int"/>
        </sequence>
    </complexType>
</schema>

=== AlexBarca/JD2018-04-11/src/by/it/kurmaz/jd02_07/Clients + xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Clients xmlns="http://it.by/kurmaz/jd02_07/xmlschema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://it.by/kurmaz/jd02_07/xmlschema Schema.xsd">
    <Client>
        <Login>Pavleg</Login>
        <Password>12345</Password>
        <Email>pavleg@tut.by</Email>
        <Address>Minsk</Address>
        <Carma>regular</Carma>
        <Order>
            <Cost>50</Cost>
               <Goods>
                   <Name>Vodka</Name>
                   <Price>5</Price>
                   <Quantity>2</Quantity>
                   <CatalogIndex>002</CatalogIndex>
               </Goods>
                <Goods>
                    <Name>Whiskey</Name>
                    <Price>10</Price>
                    <Quantity>1</Quantity>
                    <CatalogIndex>001</CatalogIndex>
                </Goods>
                <Goods>
                    <Name>Rum</Name>
                    <Price>15</Price>
                    <Quantity>2</Quantity>
                    <CatalogIndex>003</CatalogIndex>
                </Goods>
        </Order>
    </Client>

    <Client>
        <Login>Stepka</Login>
        <Password>654321</Password>
        <Email>stepan@tut.by</Email>
        <Address>Bobruysk</Address>
        <Carma>silver</Carma>
        <Order>
            <Cost>30</Cost>
            <Goods>
                <Name>Vodka</Name>
                <Price>5</Price>
                <Quantity>1</Quantity>
                <CatalogIndex>002</CatalogIndex>
            </Goods>
            <Goods>
                <Name>Cognac</Name>
                <Price>25</Price>
                <Quantity>1</Quantity>
                <CatalogIndex>004</CatalogIndex>
            </Goods>

        </Order>
    </Client>
</Clients>

=== AlexBarca/JD2018-04-11/src/by/it/rogov/jd02_07/Clients+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Clients xmlns="http://it.by/rogov/xmlschema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/rogov/xmlschema Schema.xsd"
>
    <Client>
        <Name>Alexandr</Name>
        <Password>Alexandr12345</Password>
        <Email>Alexandr12345@mail.ru</Email>
        <phone>1234098</phone>
    </Client>
    <Client>
        <Name>Oleg</Name>
        <Password>Oleg12345</Password>
        <Email>Oleg12345@mail.ru</Email>
        <phone>2340998</phone>
    </Client>
</Clients>
