=== AlexBarca/JD2018-04-11/src/by/it/kurmaz/jd02_07/Schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Clients (Client)+>
    <!ELEMENT Client (Login, Password, Email, Address, Carma, Order)>
        <!ELEMENT Login (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Carma (#PCDATA)>
        <!ELEMENT Order (Cost, Content)>
            <!ELEMENT Cost ()>
            <!ELEMENT Content (Goods)+>
                <!ELEMENT Goods (Name, Price, Quantity, CatalogIndex)>
                    <!ELEMENT Name (#PCDATA)>
                    <!ELEMENT Price ()>
                    <!ELEMENT Quantity ()>
                    <!ELEMENT CatalogIndex ()>

=== AlexBarca/JD2018-04-11/src/by/it/rogov/jd02_07/Clients+dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clients SYSTEM 'Schema.dtd'>
<Clients >
    <Client>
        <Name>Alexandr</Name>
        <Password>Alexandr12345</Password>
        <Email>Alexandr12345@mail.ru</Email>
        <phone>1234098</phone>
    </Client>
    <Client>
        <Name>Oleg</Name>
        <Password>Oleg12345</Password>
        <Email>Oleg12345@mail.ru</Email>
        <phone>2340998</phone>
    </Client>
</Clients>

=== AlexBarca/JD2018-04-11/src/by/it/kurmaz/jd02_07/Clients+dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clients SYSTEM "Schema.dtd">
<Clients>
    <Client>
        <Login>Pavleg</Login>
        <Password>12345</Password>
        <Email>pavleg@tut.by</Email>
        <Address>Minsk</Address>
        <Carma>regular</Carma>
        <Order>
            <Cost>50</Cost>
            <Content>
               <Goods>
                   <Name>Vodka</Name>
                   <Price>5 rub</Price>
                   <Quantity>2 pcs</Quantity>
                   <CatalogIndex>002</CatalogIndex>
               </Goods>
                <Goods>
                    <Name>Whiskey</Name>
                    <Price>10 rub</Price>
                    <Quantity>1 pcs</Quantity>
                    <CatalogIndex>001</CatalogIndex>
                </Goods>
                <Goods>
                    <Name>Rum</Name>
                    <Price>15 rub</Price>
                    <Quantity>2 pcs</Quantity>
                    <CatalogIndex>003</CatalogIndex>
                </Goods>
            </Content>
        </Order>
    </Client>

    <Client>
        <Login>Stepka</Login>
        <Password>654321</Password>
        <Email>stepan@tut.by</Email>
        <Address>Bobruysk</Address>
        <Carma>silver</Carma>
        <Order>
            <Cost>30</Cost>
            <Content>
                <Goods>
                    <Name>Vodka</Name>
                    <Price>5 rub</Price>
                    <Quantity>1 pcs</Quantity>
                    <CatalogIndex>002</CatalogIndex>
                </Goods>
                <Goods>
                    <Name>Cognac</Name>
                    <Price>25 rub</Price>
                    <Quantity>1 pcs</Quantity>
                    <CatalogIndex>004</CatalogIndex>
                </Goods>
            </Content>
        </Order>
    </Client>
</Clients>
