=== AlexBarca/JD2018-04-11/src/by/it/tayanovskii/jd02_07/Schema.dtd
<?xml version="1.0" encoding="UTF-8" ?>
 <!ELEMENT Readers (Reader)+>
 <!ELEMENT Reader (Login, Password, Email, Publications)>
        <!ELEMENT Login (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Publications (Publication)+>
        <!ELEMENT Publication (Title, Number, Description, Date, Price)>
        <!ELEMENT Title (#PCDATA)>
        <!ELEMENT Number (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Date (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>

=== AlexBarca/JD2018-04-11/src/by/it/tayanovskii/jd02_07/Readers+dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Readers SYSTEM 'Schema.dtd'>
<Readers>
    <Reader>
        <Login>Ivanov</Login>
        <Password>qwerty12345</Password>
        <Email>Ivanov@yandex.ru</Email>
        <Publications>
            <Publication>
                <Title>Пожарная безопасность</Title>
                <Number>1</Number>
                <Description>Контроль за пожарной безопасностью на предприятии</Description>
                <Date>2018-06-10</Date>
                <Price>10.0</Price>
            </Publication>
            <Publication>
                <Title>Охрана труда</Title>
                <Number>3</Number>
                <Description>Контроль за охраной труда на государсвенных предприятиях</Description>
                <Date>2018-05-01</Date>
                <Price>30.3</Price>
            </Publication>
        </Publications>
    </Reader>
    <Reader>
        <Login>Petrov</Login>
        <Password>12345qwerty</Password>
        <Email>Petrov@yandex.ru</Email>
        <Publications>
            <Publication>
                <Title>Охрана правопорядка</Title>
                <Number>7</Number>
                <Description>Контроль за правопорядком в общественнх местах</Description>
                <Date>2017-02-01</Date>
                <Price>40.99</Price>
            </Publication>
            <Publication>
                <Title>Охрана труда</Title>
                <Number>2</Number>
                <Description>Контроль за охраной труда на государсвенных предприятиях(июль 2018)</Description>
                <Date>2018-07-01</Date>
                <Price>30.5</Price>
            </Publication>
        </Publications>
    </Reader>
</Readers>
