=== AlexBarca/JD2018-04-11/src/by/it/mokhart/jd02_07/Schema.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT Clients (Client)+>
<!ELEMENT Client (Login, Password, Email, Clothes)>
<!ELEMENT Login (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Clothes (Cloth)+>
<!ELEMENT Cloth (Description,Price)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== AlexBarca/JD2018-04-11/src/by/it/mokhart/jd02_07/Clients+dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clients SYSTEM 'Schema.dtd'>
<Clients>
    <Client>
        <Login>Kate</Login>
        <Password>0000</Password>
        <Email>kate.d@mail.ru</Email>
        <Clothes>
            <Cloth>
                <Description>
                    Хорошая одежда, всё круто!
                </Description>
                <Price>167</Price>
            </Cloth>
            <Cloth>
                <Description>
                    Качество очень хорошее, всем советую!
                </Description>
                <Price>79</Price>
            </Cloth>
        </Clothes>
    </Client>
    <Client>
        <Login>Anton</Login>
        <Password>antonio</Password>
        <Email>an@mail.ru</Email>
        <Clothes>
            <Cloth>
                <Description>
                    Очень классные вещи, советую!
                </Description>
                <Price>193</Price>
            </Cloth>
            <Cloth>
                <Description>
                    Не лучшее качество, цена не соответсвует...
                </Description>
                <Price>118</Price>
            </Cloth>
        </Clothes>
    </Client>
</Clients>
