=== AlexBarca/JD2018-04-11/src/by/it/dkruchek/jd02_07/Company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://it.by/dkruchek/XMLSchema"
xmlns:tns="http://it.by/dkruchek/XMLSchema"
elementFormDefault="qualified">
    <element name="Company">
            <complexType>
                <sequence>
                    <element name="Director"
                             type="tns:Director"
                             minOccurs="1"
                             maxOccurs="1">
                    </element>
                    <element name="Departments"
                             type="tns:Departments"
                             maxOccurs="unbounded">
                    </element>
                </sequence>
            </complexType>
    </element>
    <complexType name="Director">
        <sequence>
            <element name="Lastname" type="string"/>
            <element name="Name" type="string"/>
            <element name="Middlename" type="string"/>
            <element name="Email" type="string"/>
            <element name="Password" type="string"/>
            <element name="Phone" type="string"/>
        </sequence>
    </complexType>
    <complexType name="Departments">

        <sequence>
            <element name="Department"
                     type="tns:Department"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>
    <complexType name="Department">

        <sequence>
            <element name="Manager"
                     type="tns:Manager"
                     maxOccurs="1">
            </element>
            <element name="Units"
                     type="tns:Units"
                     maxOccurs="unbounded">
        </element>
        </sequence>
        <attribute name="name" type="string" use="required"/>
    </complexType>

    <complexType name="Manager">
        <sequence>
            <element name="Lastname" type="string"/>
            <element name="Name" type="string"/>
            <element name="Middlename" type="string"/>
            <element name="Title" type="string"/>
            <element name="Email" type="string"/>
            <element name="Password" type="string"/>
            <element name="Vacations"
                     type="tns:Vacations"
                     minOccurs="0"
                     maxOccurs="1">
            </element>
        </sequence>
    </complexType>

    <complexType name="Units">
        <sequence>
            <element name="Unit"
                     type="tns:Unit"
                     maxOccurs="unbounded">
            </element>

        </sequence>
    </complexType>

    <complexType name="Unit">
        <sequence>
            <element name="Manager"
                     type="tns:Manager"
                     maxOccurs="1">
            </element>
            <element name="Employees"
                     type="tns:Employees"
                     maxOccurs="unbounded">
            </element>
        </sequence>
        <attribute name="name" type="string" use="required"/>

    </complexType>

    <complexType name="Employees">
        <sequence>
            <element name="Employee"
                     type="tns:Employee"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="Employee">
        <sequence>
            <element name="Lastname" type="string"/>
            <element name="Name" type="string"/>
            <element name="Middlename" type="string"/>
            <element name="Title" type="string"/>
            <element name="Email" type="string"/>
            <element name="Password" type="string"/>
            <element name="Vacations"
                     type="tns:Vacations"
                    minOccurs="0"
                    maxOccurs="1">
            </element>
        </sequence>
    </complexType>

    <complexType name="Vacation">
        <sequence>
            <element name="StartDate" type="string"/>
            <element name="EndDate" type="string"/>
            <element name="Approved" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Vacations">
        <sequence>
            <element name="Vacation"
                     type="tns:Vacation"
                     minOccurs="1"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

</schema>

=== AlexBarca/JD2018-04-11/src/by/it/dkruchek/jd02_07/Company+xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Company xmlns="http://it.by/dkruchek/XMLSchema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://it.by/dkruchek/XMLSchema Company.xsd">
    <Director>
        <Lastname>Lesnichiy</Lastname>
        <Name>Arkadii</Name>
        <Middlename>Fedorovich</Middlename>
        <Email>a.lesnichiy@company.com</Email>
        <Password>lesnichiy123</Password>
        <Phone>+375259999999</Phone>

    </Director>
    <Departments>
    <Department name="Software Development Department">
        <Manager>
            <Lastname>Sych</Lastname>
            <Name>Anatoliy</Name>
            <Middlename>Sergeevich</Middlename>
            <Title>Software Development Department Manager</Title>
            <Email>a.sych@company.com</Email>
            <Password>sych123</Password>
            <Vacations>
                <Vacation>
                    <StartDate>03.06.2018</StartDate>
                    <EndDate>14.06.2018</EndDate>
                    <Approved>true</Approved>
                </Vacation>
            </Vacations>
        </Manager>
        <Units>
        <Unit name="Low Level Programming Unit">
            <Manager>
                <Lastname>Sova</Lastname>
                <Name>Alesya</Name>
                <Middlename>Viktorovna</Middlename>
                <Title>Low Level Programming Unit Manager</Title>
                <Email>a.sova@company.com</Email>
                <Password>sova123</Password>
                <Vacations>
                    <Vacation>
                        <StartDate>01.02.2018</StartDate>
                        <EndDate>03.02.2018</EndDate>
                        <Approved>true</Approved>
                    </Vacation>
                    <Vacation>
                        <StartDate>01.05.2018</StartDate>
                        <EndDate>10.05.2018</EndDate>
                        <Approved>true</Approved>
                    </Vacation>
                </Vacations>
            </Manager>
            <Employees>
            <Employee>
                <Lastname>Filin</Lastname>
                <Name>Vitaliy</Name>
                <Middlename>Nokolaevich</Middlename>
                <Title>Junior C++ Developer</Title>
                <Email>v.filin@company.com</Email>
                <Password>filin123</Password>
                <Vacations>
                    <Vacation>
                        <StartDate>03.03.2018</StartDate>
                        <EndDate>04.03.2018</EndDate>
                        <Approved>false</Approved>
                    </Vacation>
                    <Vacation>
                        <StartDate>10.03.2018</StartDate>
                        <EndDate>11.03.2018</EndDate>
                        <Approved>false</Approved>
                    </Vacation>
                    <Vacation>
                        <StartDate>17.03.2018</StartDate>
                        <EndDate>18.03.2018</EndDate>
                        <Approved>false</Approved>
                    </Vacation>
                </Vacations>
            </Employee>
            <Employee>
                <Lastname>Korshunov</Lastname>
                <Name>Anton</Name>
                <Middlename>Antonovich</Middlename>
                <Title>Senior C++ Developer</Title>
                <Email>a.korshunov@company.com</Email>
                <Password>korshunov123</Password>
            </Employee>
            </Employees>
        </Unit>
        <Unit name="UI Unit">
            <Manager>
                <Lastname>Romashkina</Lastname>
                <Name>Anna</Name>
                <Middlename>Petrovna</Middlename>
                <Title>UI Unit Manager</Title>
                <Email>a.romashkina@company.com</Email>
                <Password>romashkina123</Password>
                <Vacations>
                    <Vacation>
                        <StartDate>09.09.2018</StartDate>
                        <EndDate>09.10.2018</EndDate>
                        <Approved>false</Approved>
                    </Vacation>
                </Vacations>
            </Manager>
            <Employees>
            <Employee>
                <Lastname>Barankina</Lastname>
                <Name>Vasilisa</Name>
                <Middlename>Pavlovna</Middlename>
                <Title>Senior UI/UX Designer</Title>
                <Email>a.barankina@company.com</Email>
                <Password>Barankina123</Password>
                <Vacations>
                    <Vacation>
                        <StartDate>09.06.2018</StartDate>
                        <EndDate>21.06.2018</EndDate>
                        <Approved>true</Approved>
                    </Vacation>
                    <Vacation>
                        <StartDate>11.11.2018</StartDate>
                        <EndDate>13.11.2018</EndDate>
                        <Approved>true</Approved>
                    </Vacation>
                </Vacations>
            </Employee>
            </Employees>
        </Unit>
        </Units>
    </Department>
    <Department name="Software Testing Department">
        <Manager>
            <Lastname>Kopytov</Lastname>
            <Name>Petr</Name>
            <Middlename>Semenovich</Middlename>
            <Title>Software Testing Department Manager</Title>
            <Email>a.kopytov@company.com</Email>
            <Password>Kopytov123</Password>
        </Manager>
        <Units>
        <Unit name="Test Automation Unit">
            <Manager>
                <Lastname>Gusarov</Lastname>
                <Name>Sergey</Name>
                <Middlename>Stepanovich</Middlename>
                <Title>Test Automation Unit Manager</Title>
                <Email>a.gusarov@company.com</Email>
                <Password>gusarov123</Password>
                <Vacations>
                    <Vacation>
                        <StartDate>12.12.2018</StartDate>
                        <EndDate>13.11.2018</EndDate>
                        <Approved>true</Approved>
                    </Vacation>
                </Vacations>
            </Manager>
            <Employees>
                <Employee>
                    <Lastname>Ovsov</Lastname>
                    <Name>Nikolay</Name>
                    <Middlename>Viktorovich</Middlename>
                    <Title>Lead Developer In Test</Title>
                    <Email>a.ovsov@company.com</Email>
                    <Password>ovsov123</Password>
                    <Vacations>
                        <Vacation>
                            <StartDate>11.01.2019</StartDate>
                            <EndDate>25.01.2019</EndDate>
                            <Approved>true</Approved>
                        </Vacation>
                    </Vacations>
                </Employee>
            </Employees>
        </Unit>
        </Units>
    </Department>
    </Departments>
</Company>
