=== AlexBarca/JD2018-04-11/src/by/it/tarasiuk/jd02_07/Sellers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it.by/tarasiuk/XMLSchemaSellers"
        xmlns:tns="http://it.by/tarasiuk/XMLSchemaSellers"
        elementFormDefault="qualified">
    <element name="Sellers">
        <complexType>
            <sequence>
                <element name="Seller"
                         type="tns:Seller"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Seller">
        <sequence>
            <element name="Email" type="string"/>
            <element name="Login" type="string"/>
            <element name="Password" type="string"/>
            <element name="Ads" type="tns:Ads"/>
        </sequence>
    </complexType>

    <complexType name="Ads">
        <sequence>
            <element name="Ad"
                     type="tns:Ad"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Ad">
        <all>
            <element name="Brand" type="string"/>
            <element name="Model" type="string"/>
            <element name="Year" type="positiveInteger"/>
            <element name="Type" type="string"/>
            <element name="Grade" type="string"/>
            <element name="Color" type="string"/>
            <element name="Price" type="tns:Price"/>
            <element name="Description" type="string"/>
        </all>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="double">
                <attribute
                        name="currency"
                        type="string"
                        use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== AlexBarca/JD2018-04-11/src/by/it/tarasiuk/jd02_09/Sellers+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Sellers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09.tarasiuk.it.by Sellers.xsd"
         xmlns="http://jd02_09.tarasiuk.it.by">
    <Seller>
        <Email>nick98@mail.ru</Email>
        <Login>Nick</Login>
        <Password>123321</Password>
        <Ads>
            <Ad>
                <Brand>AIST</Brand>
                <Model>Turbo</Model>
                <Year>2017</Year>
                <Type>adult</Type>
                <Grade>highway</Grade>
                <Color>blue</Color>
                <Price currency="USD">300.0</Price>
                <Description>Good bike!</Description>
            </Ad>
        </Ads>
    </Seller>
    <Seller>
        <Email>zohan@gmail.com</Email>
        <Login>ZiZi</Login>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Brand>Giant</Brand>
                <Model>Trance Advanced</Model>
                <Year>2016</Year>
                <Type>adult</Type>
                <Grade>mountain</Grade>
                <Color>black</Color>
                <Price currency="EUR">5500.5</Price>
                <Description>Extraordinary mountain bike!</Description>
            </Ad>
        </Ads>
    </Seller>
    <Seller>
        <Email>Lucy01@ya.ru</Email>
        <Login>ololoshka321</Login>
        <Password>fghffh03</Password>
        <Ads>
            <Ad>
                <Brand>Altair</Brand>
                <Model>City</Model>
                <Year>2006</Year>
                <Type>childish</Type>
                <Grade>city</Grade>
                <Color>red</Color>
                <Price currency="BYN">58.35</Price>
                <Description>Normal bicycle for children.</Description>
            </Ad>
        </Ads>
    </Seller>
</Sellers>
